In [2]:
import numpy as np
import numpy.linalg as la
from sympy import *
A= np.array([[2,0,1],[0,-4,0]])
print(A)
Matrix(A).rref()

[[ 2  0  1]
 [ 0 -4  0]]


(Matrix([
 [1, 0, 1/2],
 [0, 1,   0]]),
 (0, 1))

In [3]:
a=np.array([3,6,9])
b=np.array([2,5,8])
def trans1(x):
    x1=2*x[0]+x[2]
    x2=4*x[1]
    return (np.array([x1,x2]))
#=T(a+b)=T(a)+T(b)
#T(ca)=cT(a)

In [4]:
trans1(a+b)==trans1(a)+trans1(b)

array([ True,  True])

In [5]:
c=6#any number 6, 56, ...
trans1(6*a)==6*trans1(a)

array([ True,  True])

In [ ]:
##SPecial Transformation

In [6]:
rad =np.cos(np.deg2rad(45))
round(rad, 20)

0.7071067811865476

In [8]:
R=np.array([[np.cos(rad),-np.sin(rad)],
           [np.sin(rad),np.cos(rad)]])
print(np.around(R,3))

[[ 0.76 -0.65]
 [ 0.65  0.76]]


In [9]:
b=np.array([[3],[2]])
c=np.dot(R,b)
print(np.around(c,3))

[[0.981]
 [3.469]]


##Diagonalisation

$$A=PDP^{-1}$$
###A=[<1, 2>, <-4, 1>]
##D=[<5, 0>, <0, 3>]
##P=[<1, -1>, <1, -2]


In [23]:
A=np.array([[1,2],[-4,1]])
D=np.array([[5,0],[0,3]])
P=np.array([[1,-1],[1,-2]])
print(D)

[[5 0]
 [0 3]]


In [17]:
D3=np.array([[5**3,0],[0,3**3]])
print(D3)
###D=[<1, -1>, <1, -2>]

[[125   0]
 [  0  27]]


In [18]:
Arecovered=np.dot(np.dot(P,D3),la.inv(P))
print(Arecovered)

[[223. -98.]
 [196. -71.]]


In [19]:
la.matrix_power(A,3)

array([[-23, -10],
       [ 20, -23]])

In [24]:
d, P=la.eig(A)
print(d)
print(P)



[1.+2.82842712j 1.-2.82842712j]
[[0.        -0.57735027j 0.        +0.57735027j]
 [0.81649658+0.j         0.81649658-0.j        ]]


In [25]:
D=np.diag(d)
print(D)

[[1.+2.82842712j 0.+0.j        ]
 [0.+0.j         1.-2.82842712j]]


In [29]:
PDP_1=np.round(np.dot(np.dot(P,D),la.inv(P)),0)
print(PDP_1)
print(A==PDP_1)

[[ 1.-0.j  2.-0.j]
 [-4.-0.j  1.+0.j]]
[[ True  True]
 [ True  True]]


In [ ]:
#QR Decomposition