# Lecture 1: Learning to code in Python

In [6]:
import numpy as np ## Importing the numpy library
a = [1,2,3,4]
print("a",a)

a [1, 2, 3, 4]


In [3]:
print("a:=",a)

ab:= [1, 2, 3, 4]


In [27]:
A=np.array([[1,4,5],[2,8,7],[3,7,8],[4,8,7]])
print(A)

[[1 4 5]
 [2 8 7]
 [3 7 8]
 [4 8 7]]


In [35]:
## Writing a matrix
B=np.array([[1,2 ,3],
            [3, 4,5],
            [6, 7,8],
            [9,10,11]])
print("A:=",A)
print("B:=",B)


A:= [[1 4 5]
 [2 8 7]
 [3 7 8]
 [4 8 7]]
B:= [[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#Typing Mathematics using $\LaTex$
#Let try tysetting Mathematics equations given below:
    $$AX=B$$
    $$\begin[matrix] 1,2 \\ 3,4 \end [matrix]$$

In [36]:
## Sum/Addition
S=A+B
print("S=",A+B) # example of addition
print("T=", A-B) # example of substraction

S= [[ 2  6  8]
 [ 5 12 12]
 [ 9 14 16]
 [13 18 18]]
T= [[ 0  2  2]
 [-1  4  2]
 [-3  0  0]
 [-5 -2 -4]]


In [46]:
## Multiplication of matrices
M=A*B
BT=np.transpose(B)
print("A",A)
print('B',B)
print('M',M)
print('BT',np.matmul(A,BT))


A [[1 4 5]
 [2 8 7]
 [3 7 8]
 [4 8 7]]
B [[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
M [[ 1  8 15]
 [ 6 32 35]
 [18 49 64]
 [36 80 77]]
BT [[ 24  44  74 104]
 [ 39  73 124 175]
 [ 41  77 131 185]
 [ 41  79 136 193]]


In [10]:
value = 1
while value<10:
    print(value)
    value +=1

1
2
3
4
5
6
7
8
9
